# TRUE STORY MUSIC LIST
# by @b3rg3n
# Since 2024
init:
###СПИСОК
    $ music_list_ts = {}
    $ music_list_ts[" - "] = ts_muzzon + ".ogg"
###МУЗОНЫ
###ИЗ МЕНЮ
    $ music_list_ts["MND - Polar Day"] = ts_muzzon + "menu_ost/ts_pd.ogg"
    $ music_list_ts["John Murphy - Ghosts"] = ts_muzzon + "menu_ost/bad_menu_ost.ogg"
    $ music_list_ts["Darkest Time - Main Theme"] = ts_muzzon + "menu_ost/ts_killyourself.ogg"
    $ music_list_ts["Marco Beltrami - Wales"] = ts_muzzon + "menu_ost/ts_finalded.ogg"
    $ music_list_ts["Akira Yamaoka - Not Tomorrow"] = ts_muzzon + "menu_ost/good_menu_ost.ogg"
    $ music_list_ts["Intig - 10 Years Later"] = ts_muzzon + "menu_ost/pered_bad_menu_ost.ogg"
###ИЗ ЗАСТАВОК
    $ music_list_ts["Hallucinator - Mosh"] = ts_muzzon + "menu_ost/zastavka/ts_mosh.ogg"
    $ music_list_ts["Moe Era OST - Final Scene Soft"] = ts_muzzon + "menu_ost/zastavka/ts_soft.ogg"
    $ music_list_ts["wnuk2380 - Outofit"] = ts_muzzon + "menu_ost/zastavka/ts_wnuk.ogg"
    $ music_list_ts["Mudasheep - One Way or Another"] = ts_muzzon + "menu_ost/zastavka/ts_bad_credits.ogg"
    $ music_list_ts["Dead Before Down OST"] = ts_muzzon + "menu_ost/zastavka/ts_good_credits.ogg"
    $ music_list_ts["Yabai The Maid - It Always Happens No Matter What"] = ts_muzzon + "menu_ost/zastavka/ts_new_zastavka_ost_suka.ogg"
###ORIG DOKI
    $ music_list_ts["Ohayou Sayori!"] = ts_muzzon + "orig/2.ogg"
    $ music_list_ts["Ohayou Sayori! - Sayori Theme"] = ts_muzzon + "orig/2g2.ogg"
    $ music_list_ts["Main Theme - In Game"] = ts_muzzon + "orig/3.ogg"
    $ music_list_ts["Dreams of Love and Literature"] = ts_muzzon + "orig/4.ogg"
    $ music_list_ts["Okay Everyone!"] = ts_muzzon + "orig/5.ogg"
    $ music_list_ts["Okay Everyone! (Monika)"] = ts_muzzon + "orig/5_monika.ogg"
    $ music_list_ts["Okay Everyone! (Sayori)"] = ts_muzzon + "orig/5_sayori.ogg"
    $ music_list_ts["Okay Everyone! (Natsuki)"] = ts_muzzon + "orig/5_natsuki.ogg"
    $ music_list_ts["Okay Everyone! (Yuri)"] = ts_muzzon + "orig/5_yuri.ogg"
    $ music_list_ts["Okay Everyone! (Ghost)"] = ts_muzzon + "orig/5_ghost.ogg"
    $ music_list_ts["YOU WILL DIE"] = ts_muzzon + "orig/5_yuri2.ogg"
    $ music_list_ts["Okay Everyone! (Yuri & Natsuki)"] = ts_muzzon + "orig/5_yn.ogg"
    $ music_list_ts["Okay Everyone! (All)"] = ts_muzzon + "orig/5_all.ogg"
    $ music_list_ts["Play With Me"] = ts_muzzon + "orig/6.ogg"
    $ music_list_ts["kh3sdgg2kdgds6g"] = ts_muzzon + "orig/6o.ogg"
    $ music_list_ts["du3rhoef3r4iu"] = ts_muzzon + "orig/6s.ogg"
    $ music_list_ts["Daijoubu!"] = ts_muzzon + "orig/8.ogg"
    $ music_list_ts["My Feelings"] = ts_muzzon + "orig/9.ogg"
    $ music_list_ts["My Confession"] = ts_muzzon + "orig/10.ogg"
    $ music_list_ts["hufh2ojo5kpokfoej2plk"] = ts_muzzon + "orig/10-yuri.ogg"
    $ music_list_ts["Just Monika."] = ts_muzzon + "orig/m1.ogg"
###ИЗ БЛ
    $ music_list_ts["Between August and December - Awakening Power"] = ts_muzzon + "es/ts_ap.ogg"
    $ music_list_ts["Between August and December - That's our Madhouse"] = ts_muzzon + "es/ts_tom.ogg"
    $ music_list_ts["Between August and December - Doomed to be Defeated"] = ts_muzzon + "es/ts_dtbd.ogg"
    $ music_list_ts["Between August and December - Sunny Day"] = ts_muzzon + "es/ts_sd.ogg"
    $ music_list_ts["Sergey Eybog - Confession"] = ts_muzzon + "es/ts_conf.ogg"
    $ music_list_ts["Sergey Eybog - Door to Nightmare"] = ts_muzzon + "es/ts_dtn.ogg"
    $ music_list_ts["Sergey Eybog - Reflection On Water"] = ts_muzzon + "es/ts_row.ogg"
    $ music_list_ts["Sergey Eybog - always ready"] = ts_muzzon + "es/ts_ar.ogg"
    $ music_list_ts["Sergey Eybog - Eat Some Troubles"] = ts_muzzon + "es/ts_est.ogg"
    $ music_list_ts["Sergey Eybog - Meet Me There"] = ts_muzzon + "es/ts_dead_theme.ogg"
    $ music_list_ts["Sergey Eybog - A Promise From Distant Days"] = ts_muzzon + "es/ts_dist.ogg"
    $ music_list_ts["Sergey Eybog - Trapped In Dreams"] = ts_muzzon + "es/ts_dreams.ogg"
    $ music_list_ts["Sergey Eybog - Farewell To The Past"] = ts_muzzon + "es/ts_ftp.ogg"
    $ music_list_ts["Between August and December - Gentle Predator"] = ts_muzzon + "es/ts_gp.ogg"
    $ music_list_ts["Between August and December - Heather"] = ts_muzzon + "es/ts_heather.ogg"
    $ music_list_ts["Sergey Eybog - I Don't Blame You"] = ts_muzzon + "es/ts_idby.ogg"
    $ music_list_ts["Between August and December - Orchid"] = ts_muzzon + "es/ts_orchid.ogg"
    $ music_list_ts["Sergey Eybog - Reminiscences"] = ts_muzzon + "es/ts_rem.ogg"
    $ music_list_ts["Sergey Eybog - Timid Girl"] = ts_muzzon + "es/ts_tg.ogg"
    $ music_list_ts["Sergey Eybog - Just Think"] = ts_muzzon + "es/ts_think.ogg"
    $ music_list_ts["Between August and December - Torture"] = ts_muzzon + "es/ts_tor.ogg"
    $ music_list_ts["Between August and December - Faceless"] = ts_muzzon + "es/ts_faceless.ogg"
    $ music_list_ts["Sergey Eybog - Your Bright Side"] = ts_muzzon + "es/ts_ybs.ogg"
    $ music_list_ts["Sergey Eybog - You Lost Me"] = ts_muzzon + "es/ts_ylm.ogg"
    $ music_list_ts["Sergey Eybog - My Daily Life"] = ts_muzzon + "es/ts_mdl.ogg"
    $ music_list_ts["Between August and December - Glimmering Coals"] = ts_muzzon + "es/ts_gc.ogg"
    $ music_list_ts["Sergey Eybog - So Good To Be Careless"] = ts_muzzon + "es/ts_sgtbc.ogg"
    $ music_list_ts["Sergey Eybog - Afterword"] = ts_muzzon + "es/ts_afterword.ogg"
    $ music_list_ts["Sergey Eybog - I Want To Play"] = ts_muzzon + "es/ts_iwtp.ogg"
    $ music_list_ts["Sergey Eybog - Silhouette In Sunset"] = ts_muzzon + "es/ts_sis.ogg"
    $ music_list_ts["Sergey Eybog - Waltz Of Doubts"] = ts_muzzon + "es/ts_wod.ogg"
    $ music_list_ts["Sergey Eybog - Smooth Machine"] = ts_muzzon + "es/ts_sm.ogg"
    $ music_list_ts["Sergey Eybog - Dance Of Fireflies"] = ts_muzzon + "es/ts_dof.ogg"
    $ music_list_ts["Sergey Eybog - Raindrops"] = ts_muzzon + "es/ts_raindrops.ogg"
###ОСТАЛЬНОЕ

    $ music_list_ts["HCCH OST - Начало"] = ts_muzzon + "ts_emmk.ogg"
    $ music_list_ts["kelly bailey - inhuman frequency"] = ts_muzzon + "ts_hl2.ogg"
    $ music_list_ts["Pixies - Where is My Mind (piano cover)"] = ts_muzzon + "ts_gramatik.ogg"
    $ music_list_ts["Joel Nielsen - Black Mesa Theme"] = ts_muzzon + "ts_mk.ogg"
    $ music_list_ts["The Distorion - Stellar"] = ts_muzzon + "ts_stellar.ogg"
    $ music_list_ts["The Distorion - Thank God"] = ts_muzzon + "ts_tgod.ogg"
    $ music_list_ts["The Distorion - Root of all Evil"] = ts_muzzon + "ts_roae.ogg"