# DDLC ORIGINAL MUSIC DEFINES
# by @dansalvato
# Since 2024

define audio.t1 = "<loop 22.073>mod_assets/source/audio/ost/orig/1.ogg"
define audio.t2 = "<loop 4.499>mod_assets/source/audio/ost/orig/2.ogg"
define audio.t2g = "mod_assets/source/audio/ost/orig/2g.ogg"
define audio.t2g2 = "<from 4.499 loop 4.499>mod_assets/source/audio/ost/orig/2.ogg"
define audio.t2g3 = "<loop 4.492>mod_assets/source/audio/ost/orig/2g2.ogg"
define audio.t3 = "<loop 4.618>mod_assets/source/audio/ost/orig/3.ogg"
define audio.t3g = "<to 15.255>mod_assets/source/audio/ost/orig/3g.ogg"
define audio.t3g2 = "<from 15.255 loop 4.618>mod_assets/source/audio/ost/orig/3.ogg"
define audio.t3g3 = "<loop 4.618>mod_assets/source/audio/ost/orig/3g2.ogg"
define audio.t3m = "<loop 4.618>mod_assets/source/audio/ost/orig/3.ogg"
define audio.t4 = "<loop 19.451>mod_assets/source/audio/ost/orig/4.ogg"
define audio.t4g = "<loop 1.000>mod_assets/source/audio/ost/orig/4g.ogg"
define audio.t5 = "<loop 4.444>mod_assets/source/audio/ost/orig/5.ogg"
define audio.t5b = "<loop 4.444>mod_assets/source/audio/ost/orig/5.ogg"
define audio.t5c = "<loop 4.444>mod_assets/source/audio/ost/orig/5.ogg"
define audio.t6 = "<loop 10.893>mod_assets/source/audio/ost/orig/6.ogg"
define audio.t6g = "<loop 10.893>mod_assets/source/audio/ost/orig/6g.ogg"
define audio.t6r = "<to 39.817 loop 0>mod_assets/source/audio/ost/orig/6r.ogg"
define audio.t6s = "<loop 43.572>mod_assets/source/audio/ost/orig/6s.ogg"
define audio.t7 = "<loop 2.291>mod_assets/source/audio/ost/orig/7.ogg"
define audio.t7a = "<loop 4.316 to 12.453>mod_assets/source/audio/ost/orig/7.ogg"
define audio.t7g = "<loop 31.880>mod_assets/source/audio/ost/orig/7g.ogg"
define audio.t8 = "<loop 9.938>mod_assets/source/audio/ost/orig/8.ogg"
define audio.t9 = "<loop 3.172>mod_assets/source/audio/ost/orig/9.ogg"
define audio.t9g = "<loop 1.532>mod_assets/source/audio/ost/orig/9g.ogg"
define audio.t10 = "<loop 5.861>mod_assets/source/audio/ost/orig/10.ogg"
define audio.t10y = "<loop 0>mod_assets/source/audio/ost/orig/10-yuri.ogg"
define audio.td = "<loop 36.782>mod_assets/source/audio/ost/orig/d.ogg"

define audio.m1 = "<loop 0>mod_assets/source/audio/ost/orig/m1.ogg"
define audio.mend = "<loop 6.424>mod_assets/source/audio/ost/orig/monika-end.ogg"

define audio.ghostmenu = "<loop 0>mod_assets/source/audio/ost/orig/ghostmenu.ogg"
define audio.g1 = "<loop 0>mod_assets/source/audio/ost/orig/g1.ogg"
define audio.g2 = "<loop 0>mod_assets/source/audio/ost/orig/g2.ogg"
define audio.hb = "<loop 0>mod_assets/source/audio/ost/orig/heartbeat.ogg"
define audio.okevrsay = "<loop 4.444>mod_assets/source/audio/ost/orig/5_sayori.ogg"
define audio.okevryuri = "<loop 4.444>mod_assets/source/audio/ost/orig/5_yuri.ogg"
define audio.okevrnat = "<loop 4.444>mod_assets/source/audio/ost/orig/5_natsuki.ogg"
define audio.okevrnat1 = "<loop 4.444>mod_assets/source/audio/ost/orig/5_ghost.ogg"
define audio.okevrmon = "<loop 4.444>mod_assets/source/audio/ost/orig/5_monika.ogg"
