# TRUE STORY TEXT SCREENS
# by @b3rg3n
# Since 2024

init -1001 python:
    if _preferences.language == "english":
        translation=translation_en
    else:
        translation=translation_ru

    translation_new=translation


init python:
    def translation_init():
        if _preferences.language == "english":
            translation=translation_en
        else:
            translation=translation_ru
        
        translation_new=translation

init -1002 python:
    translation=translation_ru
    translation_new=translation

    def merge_two_dicts(x, y):
        z = x.copy()
        z.update(y)
        return z
    translation_temp={}
    for i,k in translation.iteritems():
        translation_temp[i]={}
        translation_temp[i][_preferences.language]=k
    translation=merge_two_dicts(translation,translation_temp)

    def get_translation(string):
        renpy.log("%s" % string )
        return translation[string][_preferences.language]

init -1003 python:
    translation_ru = {
        "Quit_confirm" : "Ты хочешь уйти,\nтак и недослушав\nмою историю?",
        "Quit_confirm_bad" : "Ты решил оставить\nвсё как есть?\nСовесть не замучает?",
        "Quit_confirm_good" : "Спасибо за уделённое время.\nВозвращайся скорее.\nНе заставляй меня скучать!",
        "Yes_quit_good" : "Скоро вернусь",
        "No_quit_good" : "Я остаюсь",
        "Yes_quit_bad" : "Прости. Прощай",
        "No_quit_bad" : "Я останусь",
        "Yes_quit" : "Вернусь позже",
        "No_quit" : "Я останусь",
        "Yes" : "Конечно",
        "No" : "Не особо",
        "Noo" : "Передумал",
        "settings" : "НАСТРОЙКИ",
        "LOAD" : "Выбери воспоминание",
        "SAVE" : "Что будешь запоминать?",
        "BACK" : "ВЕРНУТЬСЯ",
        "Back" : "Вернуться?",
        "Save_game" : "Запомнить?",
        "Delete" : "Забыть?",
        "Auto" : "Авто",
        "Empty_slot" : "Пусто",
        "Load_game" : "Вспомнить?",
        "Window_mode" : "Режим экрана",
        "Window_no_change" : "Недоступно на Android",
        "Fullscreen" : "Во весь экран",
        "Window" : "В окне",
        "Skip" : "Пропускать",
        "Skip_all" : "Вообще всё",
        "Skip_seen" : "Что уже видел",
        "Volume" : "Громкость",
        "Music_lower" : "Музыка",
        "Sound" : "Звуки",
        "Ambience" : "Фон",
        "Text_speed" : "Скорость текста",
        "Font" : "Размер шрифта",
        "Normal_font" : "Стандартный",
        "Big_font" : "Увеличенный",
        "Music_widget_set" : "Названия треков",
        "Music_widget_on" : "Включить",
        "Music_widget_off" : "Отключить",
        "Cens_mode_set" : "Без цензуры",
        "Cens_mode_off" : "Отключить",
        "Cens_mode_on" : "Включить",
        "Language" : "Язык",
        "Russian" : "Русский",
        "English" : "Английский",
        "Skippinghueta" : "Перематываю",
        "fix_hueta_energy" : "Энергосбережение",
        "fix_hueta_tearing" : "Разрыв кадров",
        "ts_discord_rpc" : "Discord RPC",
        "BG" : "Фоны",
        "CG" : "Арты",
        "ts_skip_info1" : "Режим пропуска текста.\nРаботает при зажатии CTRL\nили после нажатия правой кнопки\nна текстбоксе.",
        "ts_skip_info11" : "Режим пропуска текста.\nРаботает при свайпе вправо\nили после нажатия правой кнопки\nна текстбоксе.",
        "ts_window_info1" : "Режим вывода изображения.\nОтрисовка либо на весь экран,\nлибо в отдельном окне.\nНе работает на мобильных устройствах.",
        "ts_font_info1" : "Размер шрифта и текстбокса\n(окна, на котором выводится текст).\nДля применения\nНЕ требуется перезапуск.",
        "ts_lang_info1" : "Смена языка мода.\nДля применения\nбудет совершён\nперезапуск.",
        "ts_dicord_rpc_info1" : "Настройка активности Discord.\nОтключите, если игра вылетает при\nнестабильном соеденении с интернетом.\nДля применения будет совершён перезапуск.",
        "ts_powersave_info1" : "Настройка режима энергосбережения RenPy.\nОтключите, если наблюдаете лаги эффектов.\nВозрастает нагрузка на ЦП\n(и нагрев, соответственно).",
        "ts_tearing_info1" : "Настройка разрыва кадров RenPy.\nВключите, если ваш процессор не вывозит рендер\nсцены и наблюдаются лаги переходов.\nИспользовать с осторожностью.",
        "ts_anticens_info1" : "Убрать цензуру?\nЕсли включить - в игре будет\nприсутствовать нецензурная лексика.\nМожно изменить в любой момент игры.",
        "ts_muzzon_info1" : "Включить вывод названий играющих треков?\nОни будут показываться в меню быстрого доступа\nкоторое вызывается свайпом вверх.\nМожно изменить в любой момент игры.",
        "ts_muzzon_info2" : "Включить вывод названий играющих треков?\nОни будут показываться в меню быстрого доступа\nкоторое вызывается нажатием ПКМ.\nМожно изменить в любой момент игры.",
        "ts_crd_scr1" : "Код, эффекты, интерфейс, визуал, порт, тестирование.",
        "ts_crd_scr2" : "Нажми на кнопку чтобы открыть ВК.",
        "ts_crd_scr3" : "Сценарий, редактура, перевод на английский.",
        "ts_crd_scr4" : "Тут можно обратиться за техподдержкой",
        "ts_crd_scr5" : "и посмотреть остальные наши моды/переводы.",
        "ts_crd_scr6" : "Тут можно пообщаться с участниками сообщества",
        "ts_crd_scr7" : "и просто хорошо провести время.",
        "ts_crd_scr8" : "Сервер Discord",
        "ts_crd_vladick" : "Maddie, The Mad",
        "ts_crd_mishlent" : "BERGEN",
        "ts_crd_scr9" : "Группа в ВК",
        "ts_crd_scr10" : "Разработчики мода",
        "ts_intro_set1" : "Переходим к истории.",
        "ts_intro_set2" : "Настройка завершена.",
        "ts_intro_set3" : "Увеличить размер шрифта?",
        "ts_intro_set4" : "Или - оставить стандартный?",
        "ts_intro_set5" : "Включить вывод названий играющих треков?",
        "ts_intro_set6" : "Они будут показываться в меню быстрого доступа",
        "ts_intro_set7" : "которое вызывается свайпом вверх.",
        "ts_intro_set8" : "которое вызывается нажатием пкм.",
        "ts_intro_set9" : "Можно изменить в любой момент игры.",
        "ts_intro_set10" : "Убрать цензуру?",
        "ts_intro_set11" : "Если включить - в игре будет",
        "ts_intro_set12" : "присутствовать нецензурная лексика.",
        "ts_intro_set13" : "Можно изменить в любой момент игры.",
        "ts_intro_set14" : "Проведём небольшую",
        "ts_intro_set15" : "настройку мода.",
        "ts_dop_set1" : "Дополнительно",
        "ts_dop_set2" : "Ссылки",
        "ts_dop_set3" : "Саундтрек",
        "ts_dop_set4" : "Галерея",
        "ts_splash_set1" : "Запрещено для несовершеннолетних и",
        "ts_splash_set2" : "для слишком впечатлительных особ.",
        "ts_splash_set3" : "Яркие вспышки света и мелькающие изображения могут навредить",
        "ts_splash_set4" : "людям с высокой светочувствительностью и страдающим эпилепсией.",
        "ts_splash_set5" : "Права на использованные в моде материалы",
        "ts_splash_set6" : "принадлежат их авторам.",
        "ts_splash_set7" : "Мод никак не связан с Team Salvato.",
        "ts_splash_set8" : "Оригинальные файлы лежат на ddlc.moe",
        "ts_splash_set9" : "Ты всё ещё хочешь в это играть?",
        "ts_splash_set10" : "Серьёзно?",
        "ts_splash_set11" : "Не боишься <<сильно впечатлиться>>?",
        "ts_splash_set12" : "И не говори потом,",
        "ts_splash_set13" : "что я тебя не предупреждала.",
        "ts_splash_set14" : "Выход",
        "ts_splash_set15" : "Продолжить",
        "ts_menu_set1" : "True Story",
        "ts_menu_set2" : "Воскреснуть",
        "ts_menu_set3" : "Теперь",
        "ts_menu_set4" : "Ещё разок?",
        "ts_menu_set5" : "Сойти с ума",
        "ts_menu_set6" : "Все",
        "ts_menu_set7" : "Будут",
        "ts_menu_set8" : "Счастливы",
        "ts_menu_set9" : "Вспомнить",
        "ts_menu_set10" : "Настройки",
        "ts_menu_set11" : "Дополнительно",
        "ts_menu_set12" : "Сбежать",
        "ts_menu_set13" : "Ты доволен результатом?",
        "ts_menu_set14" : "Режим разработчика",
        "ts_menu_set15" : "Это всё - твоя вина.",
        "ts_menu_set16" : "На главную",
        "ts_menu_set17" : "Запомнить",
        "ts_menu_set18" : "Сходишь с ума уже",
        "ts_menu_set19" : "ТЫ ДОЛЖНА УМЕРЕТЬ",
        "ts_menu_mus1" : "Сейчас ничего не играет",
        "ts_menu_mus2" : "Список треков",
        "ts_credits_ending1" : "Идея, визуал, код:",
        "ts_credits_ending2" : "Сценарий:",
        "ts_credits_ending3" : "Редактура:",
        "ts_credits_ending4" : "Иллюстрации:",
        "ts_crd_fedya" : "fedor02",
        "ts_crd_cgshki" : "BayramovaRovshana",
        "ts_govno_text1" : "Начнём сначала? Или выберешь главу?",
        "ts_govno_text2" : "Начать с пролога",
        "ts_govno_text3" : "Акт первый:",
        "ts_govno_text4" : "Первая глава",
        "ts_govno_text5" : "Вторая глава",
        "ts_govno_text6" : "Третья глава",
        "ts_govno_text7" : "Четвёртая глава",
        "ts_govno_text8" : "Акт второй:",
        "ts_govno_text9" : "Акт третий:",
        "ts_govno_text10" : "Сделай нужные выборы.",
        "ts_govno_text11" : "Направляемся в нужное место.",
        "ts_govno_text228" : "Концовки",
        "ts_govno_text229"  : "Хорошая",
        "ts_govno_text230" : "Плохая",
        "ts_ctr_help1" : "Жест вправо - действие пропуска (зависит от настроек)",
        "ts_ctr_help2" : "Жест влево - открыть экран истории (прочитанный текст)",
        "ts_ctr_help3" : "Жест вверх - открыть меню быстрого доступа",
        "ts_ctr_help4"  : "Жест вниз - скрыть интерфейс",
        "ts_ctr_help5" : "Для вывода текста сценария нажми ЛКМ в любом месте экрана",
        "ts_ctr_help6" : "Для вывода дополнительного меню нажми ПКМ или ESC",
        "ts_ctr_help7" : "Для быстрого пропуска зажми CTRL (или правая кнопка на экране с текстом)",
        "ts_ctr_help8"  : "Для вывода уже прочитанного текста нажми левую кнопку на экране с текстом",
        "ts_understand" : "Я понял(а)"
}

    translation_en = {
        "Quit_confirm" : "Do you really wanna go\nwithout having listened\nto my story?",
        "Quit_confirm_bad" : "Do you really wanna\nleave all that as it is?\nWon't the conscience\neven bother you?",
        "Quit_confirm_good" : "Thank you for your time.\nCome back quicker please.\nDon't make me get bored!",
        "Yes_quit_good" : "Coming right up",
        "No_quit_good" : "I'll stay",
        "Yes_quit_bad" : "Farewell...",
        "No_quit_bad" : "I'll stay",
        "Yes_quit" : "Be right back",
        "No_quit" : "I'll stay",
        "Yes" : "Sure",
        "No" : "Not really",
        "Noo" : "Changed my mind",
        "settings" : "OPTIONS",
        "LOAD" : "Choose a memory",
        "SAVE" : "What will you remember?",
        "BACK" : "BACK",
        "Back" : "Back?",
        "Save_game" : "Remember?",
        "Delete" : "Forget?",
        "Auto" : "Auto",
        "Empty_slot" : "Empty",
        "Load_game" : "Recall?",
        "Window_mode" : "Window mode",
        "Window_no_change" : "Unavailable for Android",
        "Fullscreen" : "Full screen",
        "Window" : "Windowed",
        "Skip" : "Skipping",
        "Skip_all" : "Everything",
        "Skip_seen" : "Seen before",
        "Volume" : "Volume",
        "Music_lower" : "Music",
        "Sound" : "Sounds",
        "Ambience" : "Ambience",
        "Text_speed" : "Text speed",
        "Font" : "Font size",
        "Normal_font" : "Standard",
        "Big_font" : "Increased",
        "Music_widget_set" : "Track Widget",
        "Music_widget_on" : "Enabled",
        "Music_widget_off" : "Disabled",
        "Cens_mode_set" : "Uncensored Mode",
        "Cens_mode_off" : "Disabled",
        "Cens_mode_on" : "Enabled",
        "Language" : "Language",
        "Russian" : "Russian",
        "English" : "English",
        "Skippinghueta" : "Skipping",
        "fix_hueta_energy" : "Powersaving Mode",
        "fix_hueta_tearing" : "Tearing Mode",
        "ts_discord_rpc" : "Discord RPC",
        "BG" : "Backgrounds",
        "CG" : "CG Arts",
        "ts_skip_info1" : "Text Skipping Mode.\nWorks while holding CTRL\nor after pressing right button\non the textbox.",
        "ts_skip_info11" : "Text Skipping Mode.\nWorks when swiping right\nor after pressing right button\non the textbox.",
        "ts_window_info1" : "Window Mode.\nEither fullscreen\nor windowed mode.\nDoes not work on mobile version.",
        "ts_font_info1" : "Font And Textbox Size\n(window in which the text is displayed).\nDoes NOT require\na full reboot.",
        "ts_lang_info1" : "Language Change.\nAfter switching\nthe language\nthe game will reboot.",
        "ts_dicord_rpc_info1" : "Discord Activity Option.\nDisable it if your\ninternet connection is unstable.\nRequires a game reboot.",
        "ts_powersave_info1" : "RenPy Power Saving Mode.\nDisable it if you experience SFX lags.\nIncreases CPU usage\n(and thus your device will get heated more).",
        "ts_tearing_info1" : "RenPy Frame Skipping Mode.\nEnable it if your CPU doesn't manage\nscene rendering and your transitions are laggy.\nUse it at your own risk.",
        "ts_anticens_info1" : "Enable Uncensored Mode?\nIf you do so, there will be\na profanity in the game.\nCan be changed at any point in the game.",
        "ts_muzzon_info1" : "Enable Track Widget?\nThe music playing at the moment will be shown\nin quick menu that's called by swiping upwards.\nCan be changed at any point in the game.",
        "ts_muzzon_info2" : "Enable Track Widget?\nThe music playing at the moment will be shown\nin quick menu that's called by pressing RMB.\nCan be changed at any point in the game.",
        "ts_crd_scr1" : "Coding, SFX, interface, visuals, mobile porting, testing.",
        "ts_crd_scr2" : "Press to open VK page.",
        "ts_crd_scr3" : "Writing, editing, translating to English.",
        "ts_crd_scr4" : "Here you can call for support",
        "ts_crd_scr5" : "and see our other mods/translations.",
        "ts_crd_scr6" : "Here you can chat with other community members",
        "ts_crd_scr7" : "and simply pass time.",
        "ts_crd_scr8" : "Discord server",
        "ts_crd_vladick" : "Maddie, The Mad",
        "ts_crd_mishlent" : "BERGEN",
        "ts_crd_scr9" : "VK group",
        "ts_crd_scr10" : "Mod Developers",
        "ts_intro_set1" : "Let's move on to the story.",
        "ts_intro_set2" : "First launch setting completed.",
        "ts_intro_set3" : "Increase font size?",
        "ts_intro_set4" : "Or keep the standard one?",
        "ts_intro_set5" : "Enable Track Widget for music played at the moment?",
        "ts_intro_set6" : "Tracks will be shown in quick menu",
        "ts_intro_set7" : "that's called by swiping upwards.",
        "ts_intro_set8" : "that's called by pressing RMB.",
        "ts_intro_set9" : "Can be changed at any point in the game.",
        "ts_intro_set10" : "Enable Uncensored Mode?",
        "ts_intro_set11" : "When enabled, there will be",
        "ts_intro_set12" : "some sort of profanity in the game.",
        "ts_intro_set13" : "Can be changed at any point in the game.",
        "ts_intro_set14" : "Let's start with a",
        "ts_intro_set15" : "little mod setting, shall we?",
        "ts_dop_set1" : "Extras",
        "ts_dop_set2" : "Links",
        "ts_dop_set3" : "Soundtrack",
        "ts_dop_set4" : "Gallery",
        "ts_splash_set1" : "This game is very not suitable for children",
        "ts_splash_set2" : "or those who are easily disturbed.",
        "ts_splash_set3" : "Flashes of light and twitching images can harm",
        "ts_splash_set4" : "people with photosensitivity and those who suffer from epilepsy.",
        "ts_splash_set5" : "All rights for assets presented in this mod",
        "ts_splash_set6" : "belong to their respective authors.",
        "ts_splash_set7" : "Mod is not in any way affiliated with Team Salvato.",
        "ts_splash_set8" : "Original game files are required to play the mod and can be found at ddlc.moe",
        "ts_splash_set9" : "Do you still want to play this?",
        "ts_splash_set10" : "Like, seriuosuly?",
        "ts_splash_set11" : "Unafraid of <<being impressed too much>>?",
        "ts_splash_set12" : "Don't say that",
        "ts_splash_set13" : "I didn't warn you.",
        "ts_splash_set14" : "Quit now",
        "ts_splash_set15" : "Proceed ",
        "ts_menu_set1" : "True Story",
        "ts_menu_set2" : "Resurrect",
        "ts_menu_set3" : "Now",
        "ts_menu_set4" : "Another one?",
        "ts_menu_set5" : "Lose mind",
        "ts_menu_set6" : "Everyone",
        "ts_menu_set7" : "Can be",
        "ts_menu_set8" : "Happy",
        "ts_menu_set9" : "Recall",
        "ts_menu_set10" : "Options",
        "ts_menu_set11" : "Extras",
        "ts_menu_set12" : "Escape",
        "ts_menu_set13" : "Satisfied with the outcome?",
        "ts_menu_set14" : "Developer mode",
        "ts_menu_set15" : "This is all your own damn fault.",
        "ts_menu_set16" : "Main menu",
        "ts_menu_set17" : "Remember",
        "ts_menu_set18" : "Losing your mind for",
        "ts_menu_set19" : "ALL MUST DIE. YOU FIRST",
        "ts_menu_mus1" : "Nothing is currently playing",
        "ts_menu_mus2" : "Track list",
        "ts_credits_ending1" : "Idea, visuals, coding:",
        "ts_credits_ending2" : "Writing:",
        "ts_credits_ending3" : "Editing:",
        "ts_credits_ending4" : "CG Arts:",
        "ts_crd_fedya" : "fedor02",
        "ts_crd_cgshki" : "BayramovaRovshana",
        "ts_govno_text1" : "Start all over or choose a specific chapter?",
        "ts_govno_text2" : "Start all over",
        "ts_govno_text3" : "Act One:",
        "ts_govno_text4" : "Chapter One",
        "ts_govno_text5" : "Chapter Two",
        "ts_govno_text6" : "Chapter Three",
        "ts_govno_text7" : "Chapter Four",
        "ts_govno_text8" : "Act Two:",
        "ts_govno_text9" : "Act Three:",
        "ts_govno_text10" : "Make your choices.",
        "ts_govno_text11" : "Moving on to a requested place.",
        "ts_govno_text228" : "Endings",
        "ts_govno_text229"  : "Good Ending",
        "ts_govno_text230" : "Bad Ending",
        "ts_ctr_help1" : "Swipe right to skip the dialogue (depending on the settings)",
        "ts_ctr_help2" : "Swipe left to open history screen (seen text)",
        "ts_ctr_help3" : "Swipe up to access quick menu",
        "ts_ctr_help4"  : "Swipe down to hide UI",
        "ts_ctr_help5" : "Press LMB at any place on the screen for the text output",
        "ts_ctr_help6" : "Press RMB or ESC to access quick menu",
        "ts_ctr_help7" : "Hold CTRL (or right button on the text screen) to skip the text",
        "ts_ctr_help8"  : "Press left button on the text screen to access history screen",
        "ts_understand" : "I understand"
}